version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bankdb
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: flask-app
    depends_on:
      - db
    ports:
      - "5000:5000"
